import { Are_You_Serious, Inter, Staatliches } from "next/font/google";
import "./globals.css";
import { setupFsCheck } from "next/dist/server/lib/router-utils/filesystem";
import { OPTIMIZED_FONT_PROVIDERS } from "next/dist/shared/lib/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}